### PR TITLE
Fix create string dependency

### PR DESCRIPTION
**Pull request by franklupo**

### CODE REVIEW

**Comment by franklupo** [comment]
Current:

> Depends: , libc6, libcurl3, libgcc1, libgssapi-krb5-2, liblttng-ust0, libssl0.9.8 | libssl1.0.0 | libssl1.0.1 | libssl1.0.2, libstdc++6, libunwind8, libuuid1, zlib1g, libicu52 | libicu53 | libicu54 | libicu55 | libicu56 | libicu57 | libicu58 | libicu59

**Comment by qmfrederik** [comment]
@franklupo Thanks! Would you mind adding a unit test for this?

**Comment by franklupo** [comment]
@qmfrederik I'm not very good at unit tests.

**Comment by qmfrederik** [comment]
OK - we'll get to it later then ;-)

**Pull request merged**
