### PR TITLE
Deb support

### PR DESCRIPTION
**Pull request by kekekeks**
Still need to implement `dotnet-deb` (I can't run your CLI tools on my machine, unfortunately, probably something wrong with SDK). Other than that packages installs and `systemd` service gets created.

Lintian report:
```
E: demo: arch-dependent-file-in-usr-share usr/share/demo/System.Globalization.Native.so
E: demo: unstripped-binary-or-object usr/share/demo/System.Globalization.Native.so
E: demo: arch-dependent-file-in-usr-share usr/share/demo/System.IO.Compression.Native.so
E: demo: arch-dependent-file-in-usr-share usr/share/demo/System.Native.a
E: demo: arch-dependent-file-in-usr-share ... use --no-tag-display-limit to see all (or pipe to a file/program)
E: demo: unstripped-binary-or-object usr/share/demo/createdump
E: demo: unstripped-binary-or-object usr/share/demo/libclrjit.so
W: demo: hardening-no-relro usr/share/demo/libclrjit.so
E: demo: unstripped-binary-or-object ... use --no-tag-display-limit to see all (or pipe to a file/program)
W: demo: hardening-no-relro usr/share/demo/libcoreclr.so
E: demo: changelog-file-missing-in-native-package
E: demo: no-copyright-file
E: demo: description-starts-with-package-name
E: demo: description-too-short demo.1.0.102.22979.ubuntu.16.04-x64
E: demo: extended-description-is-empty
W: demo: no-section-field
W: demo: no-priority-field
W: demo: missing-intermediate-directory etc/
W: demo: missing-intermediate-directory etc/demo/
W: demo: non-standard-file-perm etc/demo/appsettings.json 0444 != 0644
W: demo: missing-intermediate-directory etc/systemd/
W: demo: missing-intermediate-directory ... use --no-tag-display-limit to see all (or pipe to a file/program)
W: demo: non-standard-file-perm etc/systemd/system/demo.service 0444 != 0644
W: demo: non-standard-file-perm usr/share/demo/BouncyCastle.Crypto.dll 0444 != 0644
W: demo: non-standard-file-perm ... use --no-tag-display-limit to see all (or pipe to a file/program)
W: demo: extra-license-file usr/share/demo/wwwroot/lib/bootstrap/LICENSE
W: demo: extra-license-file usr/share/demo/wwwroot/lib/jquery-validation/LICENSE.md
W: demo: extra-license-file usr/share/demo/wwwroot/lib/jquery/LICENSE.txt
W: demo: embedded-javascript-library usr/share/demo/wwwroot/lib/jquery/dist/jquery.js please use libjs-jquery
W: demo: embedded-javascript-library usr/share/demo/wwwroot/lib/jquery/dist/jquery.min.js please use libjs-jquery
E: demo: dir-or-file-in-var-run var/run/demo
E: demo: shlib-with-executable-bit usr/share/demo/System.Globalization.Native.so 0755
E: demo: shlib-with-executable-bit usr/share/demo/System.IO.Compression.Native.so 0755
E: demo: shlib-with-executable-bit usr/share/demo/System.Native.so 0755
E: demo: shlib-with-executable-bit ... use --no-tag-display-limit to see all (or pipe to a file/program)
E: demo: systemd-service-file-outside-lib etc/systemd/system/demo.service

```

Those errors/warnings are related to package contents, I don't think we can do much about that.

### CODE REVIEW

**Comment by qmfrederik** [comment]
@kekekeks Thanks! Overall, looks really good to me.

There are merge conflicts, though. Can you rebase this on top off master?

**Comment by kekekeks** [comment]
I think, I've updated it to the latest master by this commit https://github.com/qmfrederik/dotnet-packaging/pull/20/commits/40cbeda06808f27100bf3300265705c15e6150d4 , so there shouldn't be any conflicts.

Or do you prefer linear history? Linear history isn't good, because `git rebase` destroys information. It alters commits, so they won't contain the same snapshot of the code they had before rebase. That really messes up `git bisect`, since it won't be able to identify commit that actually broke something.

**Comment by kekekeks** [comment]
Basically I want a way to disable `nearest-wins` policy completely and have `satisfy-all-dependencies` policy instead.

**Comment by qmfrederik** [comment]
Merged via 9307318d29482aee47030636c167649e002f1259

**Comment by qmfrederik** [comment]
@kekekeks There were still some merge conflicts, so I rebased this PR on master & merged it via 9307318d29482aee47030636c167649e002f1259. As to `git rebase`, you don't want to do it on `master` or anything similar but on PRs it should be fine.

**Pull request closed without merging**
