### PR TITLE
Update Packaging.Targets.targets

### PR DESCRIPTION
**Pull request by darkneil14**
Updated Packaging.Targets.targets to be able to override Release. Apparently even when specifying a value for Release property it is always reading the value 0.

### CODE REVIEW

**Comment by darkneil14** [comment]
@qmfrederik just wondering when will this be merge?. Thanks!

**Comment by qmfrederik** [comment]
Apologies. I realized I was wrong when I asked you to try to get rid of the `<Release>` value. I merged the first commit into master via 9318b1833560cc1cfd3f6a9428dc8c12d59ad9b9.

A release should flow to NuGet shortly; let me know if this works for you.

**Comment by mikaelmello** [comment]
Perhaps this PR should be closed?

**Comment by qmfrederik** [comment]
@mikaelmello Yes it should; the changes were merged independently. Thanks for the reminder!

**Pull request closed without merging**
