### PR TITLE
(doc) Minor corrections

### PR DESCRIPTION
**Pull request by gep13**

### CODE REVIEW

**Comment by gep13** [comment]
@qmfrederik very interesting project!  Was just reading through the readme, and noticed a couple things that I thought needed correcting.

Let me know if you have any questions.

**Comment by qmfrederik** [comment]
@gep Thanks! Hope you find the project useful, if you have questions/feedback/... let me know ;-)

**Comment by gep** [comment]
@qmfrederik you mentioned the wrong person

**Comment by qmfrederik** [comment]
@gep13 Thanks! Hope you find the project useful, if you have questions/feedback/... let me know ;-)
@gep Apologies!

**Comment by gep13** [comment]
@gep apologies, this seems to happen from time to time.  I normally point it out when I notice it.

**Pull request merged**
