### PR TITLE
Add support for net9.0

### PR DESCRIPTION
**Pull request by CorruptComputer**
Used #246 as a guide for what needed to change.

net6.0 and net7.0 are out of support now and are probably safe to remove, left those in since that seemed like it should be outside the scope of this PR to me.

### CODE REVIEW

**Comment by CorruptComputer** [comment]
@qmfrederik Apologies for the ping, however I have been unable to deploy my app since upgrading to .NET 9 due to this not being supported. Could you please review this and let me know if I need to change anything else?

**Comment by sduffy77** [comment]
+1 to this. We could use NET 9 support as well. I rolled our application back to NET 8 until this is resolved.

**Comment by CorruptComputer** [comment]
Sadly I am not able to roll back to .NET 8 as I've added some of the new features in .NET Aspire 9 to make development and testing a bit easier. So until this is released I'm stuck unable to build the .rpm packages for my application, thankfully its still in a somewhat early development phase so deployment isn't really needed outside of testing currently.

If this gets closer to the time I'm ready to release my first version and still isn't merged I may just hard fork this repo and maintain my own build of it on nuget.org.

**Comment by qmfrederik** [comment]
@CorruptComputer Would you mind to rebase this PR so we get CI going?

**Comment by CorruptComputer** [comment]
Sure no problem at all, should be rebased now.

**Comment by qmfrederik** [comment]
Thanks @CorruptComputer !

**Comment by qmfrederik** [comment]
Version 0.1.226 should be live on NuGet.

**Pull request merged**
